moonstuff/urls.py
from django.urls import re_path

from . import views

app_name = "moonstuff"

urlpatterns = [
    re_path(r'^$', views.dashboard, name='dashboard'),
    re_path(r'^scan/$', views.add_scan, name='add_scan'),
    re_path(r'^track/$', views.add_character, name='add_character'),
    re_path(r'^info/(?P<moon_id>[0-9]+)/$', views.moon_info, name='view_moon')
]

moonstuff/models.py
from django.db import models
from datetime import timedelta


from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo
from eveuniverse.models import EveMoon, EveType


# Create your models here.
class Moonstuff(models.Model):

    class Meta:
        managed = False
        default_permissions = (())
        permissions = (
            ('access_moonstuff', 'Allows access to the moonstuff module'),
            ('access_moon_list', 'Allows access to list of all moons.'),
        )


class Resource(models.Model):
    ore = models.ForeignKey(EveType, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=11, decimal_places=10)
    moon = models.ForeignKey(EveMoon, on_delete=models.CASCADE, related_name='resources')

    @property
    def rarity(self):
        """
        Determine the rarity of the resource by its group_id. (Default is 0)
        :return:
        """
        rs = {1884: 4, 1920: 8, 1921: 16, 1922: 32, 1923: 64}
        return rs.get(self.ore.eve_group_id, 0)

    def __str__(self):
        return f"{self.ore.name} x {self.quantity} ({self.moon.name})"

    class Meta:
        default_permissions = ('add',)


class Refinery(models.Model):
    structure_id = models.BigIntegerField(primary_key=True)
    evetype = models.ForeignKey(EveType, on_delete=models.CASCADE)
    name = models.CharField(null=True, max_length=255)  # Might not actually need this.
    corp = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE, related_name='refineries')
    observer = models.BooleanField(default=True)

    def __str__(self):
        if self.name is None:
            return f'Unknown Structure ID{self.structure_id} ({self.evetype.name})'
        return f'{self.name}'

    class Meta:
        default_permissions = (())
        verbose_name_plural = "Refineries"


class TrackingCharacter(models.Model):
    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE)
    latest_notification_id = models.BigIntegerField(null=True, default=0)
    last_notification_check = models.DateTimeField(null=True)

    def __str__(self):
        return f'{self.character.character_name}'

    class Meta:
        default_permissions = ('add',)


class Extraction(models.Model):
    start_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    decay_time = models.DateTimeField()
    moon = models.ForeignKey(EveMoon, on_delete=models.CASCADE, related_name='extractions')
    refinery = models.ForeignKey(Refinery, on_delete=models.CASCADE, related_name='extractions')
    corp = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE, related_name='extractions')
    cancelled = models.BooleanField(null=False, default=False)
    jackpot = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    depleted = models.BooleanField(default=False)
    total_volume = models.BigIntegerField(null=True)

    @property
    def despawn(self):
        """
        Returns the latest despawn time. Actual despawn can be up to -3h from returned time depending on when the
            moon drill laser was fired. Actual despawn should never occur after returned time however.
        :return:
        """
        return self.decay_time + timedelta(hours=48)

    class Meta:
        default_permissions = (())
        unique_together = (('start_time', 'moon'),)


class LedgerEntry(models.Model):
    observer = models.ForeignKey(Refinery, on_delete=models.CASCADE, related_name='entries')
    character_id = models.IntegerField()  # There is no guarantee that we will have a character object for this.
    last_updated = models.DateField()
    quantity = models.BigIntegerField()
    recorded_corporation_id = models.IntegerField()
    evetype = models.ForeignKey(EveType, on_delete=models.CASCADE, related_name='ledger_entries')

    class Meta:
        default_permissions = (())
        # For each observer we only want one record per day per character per ore type.
        unique_together = (('observer', 'last_updated', 'character_id', 'evetype'),)

moonstuff/templates/moonstuff/add_scan.html
{% extends 'moonstuff/base.html' %}
{% load i18n %}

{% block moon_title %} {% translate 'Add Scan' %} {% endblock %}

{% block moon_block %}
    <div class="container-fluid">
        <div class="panel panel-primary">
            <div class="panel-heading"> {% translate "Moon Scan Input" %} </div>
            <div class="panel-body">
                <form role="form" method="post" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" name="scan" id="scanBox" rows="10" cols="15" required aria-required="true"></textarea>
                    </div>
                    <br />
                    <button type="submit" role="button" class="btn btn-block btn-primary" name="submit_scan" id="submit_scan">
                        {% translate "Submit Moon Scan(s)" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

moonstuff/templates/moonstuff/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block title %}{% block moon_title %}{% endblock %} - {% translate "Moonstuff" %}{% endblock %}

{% block content %}
    <div class="col-lg-12" style="padding: 0 !important;">
        <br />
        <div class="col-lg-12 container-fluid">
            {% include 'moonstuff/menu.html' %}
            {% block moon_block %}{% endblock %}
        </div>
    </div>
{% endblock %}

moonstuff/templates/moonstuff/dashboard.html
{% extends 'moonstuff/base.html' %}
{% load i18n %}
{% load humanize %}
{% load evelinks %}

{% block moon_title %} {% translate 'Dashboard' %} {% endblock %}

{% block moon_block %}
    <div class="container-fluid">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#extractions">Upcoming Extractions</a></li>
            {% if perms.moonstuff.access_moon_list %}<li><a data-toggle="tab" href="#moons">List Moons</a></li>{% endif %}
        </ul>
        <div class="tab-content panel panel-default" style="border-top-left-radius: 0 !important; border-top-right-radius: 0 !important;">
            <div id="extractions" class="tab-pane fade in active panel-default">
                <div style="margin-left: 15px; margin-top: 10px;">
                    <ul class="nav nav-pills">
                        {% if default_view == "Calendar" %}
                        <li class="active"><a data-toggle="tab" href="#exCal">Calendar View</a></li>
                        <li><a data-toggle="tab" href="#exCard">Card View</a></li>
                        {% else %}
                        <li class="active"><a data-toggle="tab" href="#exCard">Card View</a></li>
                        <li><a data-toggle="tab" href="#exCal">Calendar View</a></li>
                        {% endif %}

                    </ul>
                </div>
                <div class="tab-content">
                    <div id="exCal" class="tab-pane fade in {% if default_view == "Calendar" %}active{% endif %} panel-default">
                        <div class="panel-body">
                            <div id="calendar"></div>
                        </div>
                    </div>
                    <div id="exCard" class="tab-pane fade in {% if default_view == "Card" %}active{% endif %} panel-default">
                        <div class="panel-body">
                            <p style="padding-left: 15px;"><i>All times are UTC</i></p>
                            <div class="flex-container">{% for ext in extractions %}
                                {% if ext|check_visibility %}
                                {% else %}
                                <div class="col-md-4">
                                    <div class="panel panel-ext text-center" {% if ext.jackpot %} style="box-shadow: 1px 1px 10px #6ae766, 1px 1px 10px #8dd279;" {% endif %}>
                                        {% if ext.jackpot %}
                                            <div class="ribbon">
                                                <span>JACKPOT</span>
                                            </div>
                                        {% endif %}
                                        <div class="panel-heading">
                                            <a class="info-link" href="#" data-toggle="modal" data-target="#moonModal" data-url="{% url 'moonstuff:view_moon' ext.moon.id %}">
                                                <h4 style="margin-top: 0;">
                                                    {{ ext.refinery.name }}
                                                </h4>
                                                <h5>{{ ext.moon.name }}</h5>
                                            </a>
                                        </div>
                                        <div class="panel-body">
                                            {% for res in ext.moon.resources.all|card_labels %}
                                                <span class="label bg-R{{ res }}">R{{ res }}</span>
                                            {% endfor %}
                                            <hr/>
                                            <ul style="list-style-type: none; padding-left: 0;">
                                                <li><strong>Chunk Time: {{ ext|chunk_time }} days</strong></li>
                                                {% if not ext.active %}
                                                <li>Chunk Arrival: {{ ext.arrival_time|date:"Y-n-j h:i" }}</li>
                                                <li>Self Destructs: {{ ext.decay_time|date:"Y-n-j h:i" }}</li>
                                                {% else %}
                                                <li>
                                                    <div class="alert alert-info">
                                                        <strong>MINING ACTIVE</strong>
                                                    </div>
                                                </li>
                                                {% endif %}
                                            </ul>
                                            <hr />
                                            {% for res in ext.moon.resources.all|order_quantity %}
                                                <img src="{{ res.ore.id|type_icon_url:32 }}" /> {{ res.ore.name }} <span class="label bg-R{{ res.rarity }}">R{{ res.rarity }}</span> <i style="font-size: 80% !important">{{ resources|get_item:res.ore.id|floatformat:2|intcomma }} isk/m<sup>3</sup></small></i>
                                                <div class="progress">
                                                    <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ res.quantity|percent }}%;">
                                                        <h5 class="media-heading percent">{{ res.quantity|percent }}% </h5>
                                                    </div>
                                                </div>
                                                <br />
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if perms.moonstuff.access_moon_list %}
            <div id="moons" class="tab-pane fade in panel-default">
                <div class="panel-body">
                    <table id="moonList" class="table table-striped" style="width: 100% !important;">
                        <thead>
                            <th>Moon</th>
                            <th>Refinery</th>
                            <th>Owner</th>
                            <th>System</th>
                            <th>Region</th>
                            <th>Next Extraction</th>
                            <th>Rarity</th>
                            <th>Utilities</th>
                            <th>Ores</th>
                        </thead>
                        <tbody>
                            {% for moon in moons %}
                                <tr>
                                    <td>{{ moon.name }}</td>
                                    <td>{{ moon|get_refinery_name }}</td>
                                    <td><img src="{{ moon|get_refinery_owner_id|corporation_logo_url:32 }}">{{ moon|get_refinery_owner_name}}</td>
                                    <td><a href="https://evemaps.dotlan.net/system/{{ moon.eve_planet.eve_solar_system.name}}">{{ moon.eve_planet.eve_solar_system.name }}</a></td>
                                    <td>{{ moon.eve_planet.eve_solar_system.eve_constellation.eve_region.name }}</td>
                                    <td>{{ moon|get_next_extraction }}</td>
                                    <td>{% for res in moon.resources.all|card_labels %} <span class="label bg-R{{ res }}">R{{ res }}</span> {% endfor %}</td>
                                    <td><a href="{% url 'moonstuff:view_moon' moon.id %}" class="btn btn-primary"><span class="far fa-eye"></span></a></td>
                                    <td>{% for ore in moon.resources.all %}{{ ore.ore.name }}{% endfor %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    {# Modal #}
    <div class="modal fade" tabindex="-1" role="dialog" id="moonModal" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="container-fluid" id="moonModalBody">

                    </div>
                </div>
            </div>
        </div>
    </div>
    {# End Modal #}
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/moment-js.html' %}
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.10.2/dist/fullcalendar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.10.2/dist/locale-all.min.js"></script>
{% endblock %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@3.10.2/dist/fullcalendar.min.css">
    <link rel="stylesheet" href="/static/moonstuff/css/style.css">
{% endblock %}

<script>
{% block extra_script %}
$(function() {
    // Define calendar color key
    let rarColors = {
        "R0": "bg-R0",
        "R4": "bg-R4",
        "R8": "bg-R8",
        "R16": "bg-R16",
        "R32": "bg-R32",
        "R64": "bg-R64",
    };

    // Build calendar color key
    let key = "<p style='margin: -1px;'><i>All times are UTC</i></p><br >"
    for (const [k, v] of Object.entries(rarColors)){
        key += "<span class='label fc-lbl "+v+"'>"+k+"</span>"
    }

    // Define the locale for the calendar
    let cookie = Object.fromEntries(document.cookie.split('; ').map(v=>v.split('=').map(decodeURIComponent)));
    try{
        locale = cookie.django_language.substr(0,2);
    }
    catch (RefrenceError) {
        locale = "en";
    }

    // Build Calendar
    $('#calendar').fullCalendar({
        locale: locale,
        timezone: 'UTC',
        now: moment.utc(),
        defaultView: 'month',
        themeSystem: 'bootstrap3',
        events: {{ events|safe }},
        header: {
            left: '',
            center: 'title',
            right: 'today prev,next',
        },
        eventRender: function(event, element, view) {
            if(event.rarity.length == 0){
                rarity = "R0";
            }
            else {
               rarity = "R"+Math.max(...event.rarity);
            }

            element.popover({
                title: event.moon,
                content: "Click for more details!",
                trigger: 'hover',
                placement: 'top',
                container: 'body'
            })

            element.css({
                backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--'+rarity),
                borderColor: getComputedStyle(document.documentElement).getPropertyValue('--'+rarity),
            })

            element.attr('data-toggle', 'modal');
            element.attr('data-target', '#moonModal');
            element.attr('data-url', '/moons/info/'+event.moon_id);
            element.attr('href', '#');

        },
        dayRender: function(day, cell) {
          if(day.isSame(moment.utc(), 'day')){
              cell[0].classList.remove('alert');
              cell[0].classList.remove('alert-info');
              cell[0].classList.add('bgd');
          }
        },
        timeFormat: 'H(:mm)'
    })
    // Add the key to the calendar
    $('#calendar > div.fc-toolbar.fc-header-toolbar > div.fc-left').html(key);

    $('#extractions').on('shown.bs.tab', 'a[data-toggle="tab"]', function (e) {
        if (e.target.hash === '#exCal') {
            $('#calendar').fullCalendar('render');
        }
    });

    {% if perms.moonstuff.access_moon_list %}
    // DataTable
    $('#moonList').DataTable({
        columnDefs: [
            {
                targets: [ 8 ],
                visible: false
            }
        ]
    });
    {% endif %}

    // Ajax Modals
    $('#moonModal').on('show.bs.modal', function (e) {
       var modal = $(e.target);
       var title = modal.find('.modal-title').empty();
       var head = modal.find('.modal-header');
       var body = modal.find('#moonModalBody').empty();

       $.ajax($(e.relatedTarget).data('url'))
         .done(function (data){
             modal.find('.modal-body').removeClass('bg-danger')
             title.html($(data).find('#title'));
             body.html($(data).find('#content'));
         })
         .fail(function (xhr, status, errorThrown) {
             head.addClass('bg-danger');
             modal.find('.modal-body').addClass('bg-danger');
             title.html("Error!");
             body.html("There was an error loading the data for the requested moon.");
         });

    });

    // Activate datatables in modals.
    $('#moonModal').on('shown.bs.modal', function() {
        $('#pastTable').DataTable({
            'bFilter': false,
            "sScrollY": "220px",
            "bPaginate": false
        });
    })

})
{% endblock %}
</script>

moonstuff/templates/moonstuff/menu.html
{% load i18n %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% translate "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'moonstuff:dashboard' %}">{% translate "Moons" %}</a>
        </div>
         {% if perms.moonstuff.add_trackingcharacter %}
            <div class="dropdown pull-right" style="margin-top: .8em;">
                <button class="btn btn-success btn-sm dropdown-toggle" type="button" id="manageDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="fa fa-plus"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="manageDrop">
                    <li> <a href="{% url 'moonstuff:add_scan' %}">{% translate "Moon Scan" %}</a></li>
                    <li> <a href="{% url 'moonstuff:add_character' %}">{% translate "Tracking Character" %}</a></li>
                </ul>
            </div>
        {% endif %}
    </div>
</nav>

moonstuff/templates/moonstuff/moon_info.html
{% extends 'moonstuff/base.html' %}
{% load i18n %}
{% load evelinks %}

{% block moon_title %} {% translate 'Moon Info' %} - {{ moon.name }} {% endblock %}

{% block moon_block %}
    {% include 'moonstuff/moon_info_ajax.html' %}
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/moment-js.html' %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="/static/moonstuff/css/style.css">
    {% include 'bundles/datatables-css.html' %}
{% endblock %}

<script>
    {% block extra_script %}
        $(function() {
                $('#pastTable').DataTable({
                    'bFilter': false,
                    "sScrollY": "220px",
                    "bPaginate": false
                });
            });
    {% endblock %}
</script>

moonstuff/templates/moonstuff/moon_info_ajax.html
{% load i18n %}
{% load humanize %}
{% load evelinks %}

<div>
    <h2><span id="title">{{ moon.name }}</span></h2>

    <br />

    <div class="col-md-12" id="content" >
        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-info">
                    <div class="panel-heading">Resources</div>
                    <div class="panel-body">
                        {% for res in moon.resources.all|order_quantity %}
                            <img src="{{ res.ore.id|type_icon_url:32 }}" /> {{ res.ore.name }} <span class="label bg-R{{ res.rarity }}">R{{ res.rarity }}</span> <i style="font-size: 80% !important;">{{ resources|get_item:res.ore.id|floatformat:2|intcomma }} isk/m<sup>3</sup></i>
                            <div class="progress" style="margin-left: 0;">
                                <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ res.quantity|percent }}%;">
                                    <h5 class="media-heading percent">{{ res.quantity|percent }}% </h5>
                                </div>
                            </div>
                            <br />
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="panel panel-default">
                    <div class="panel-heading">Extractions</div>
                    <div class="panel-body">
                        <table class="table table-striped" id="pastTable">
                            <thead>
                                <th>Date</th>
                                <th>Jackpot?</th>
                            </thead>
                            <tbody>
                                {% for ext in moon.extractions.all.reverse%}
                                    <tr>
                                        <td>{{ ext.arrival_time|date:"Y-n-j h:i" }}</td>
                                        <td>
                                            {% if ext.jackpot %}
                                                <span class="fas fa-check"></span>
                                            {% else %}
                                                <span class="fas fa-times"></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>